---
- hosts: checkbox
  gather_facts: no
  become: yes

  tasks:

  - name: Get credentials from vault
    include_vars:
      file: /var/lib/jenkins/password.yml
      name: vault

  - name: Update all packages
    apt:
      update_cache: yes
      upgrade: dist

  - name: Add source key for nodejs
    apt_key:
      url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
      state: present
    register: first_run

  - name: Add source repo for nodejs
    apt_repository:
      repo: "deb https://deb.nodesource.com/node_8.x xenial main"
      state: present
      update_cache: yes    

  - name: Install packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - nginx
      - mongodb
      - nodejs
      - python3-pip

  - name: install pymongo
    pip:
      name: pymongo
      state: present

  - name: add mongo user
    mongodb_user:
      database: admin
      name: "{{ vault['mongo_user'] }}"
      password: "{{ vault['mongo_pass'] }}"
      roles: userAdminAnyDatabase
      state: present
    #when: first_run|changed
  
  - name: Restart mongo
    service:
      name: mongodb
      state: restarted
    #when: first_run|changed

  - name: clone checkbox repo
    git:
      repo: https://github.com/thegreyd/checkbox.io
      dest: /home/ubuntu/checkbox
      force: yes
      update: yes

  - name: configure nginx defaults
    copy:
      src: /home/ubuntu/checkbox/local-conf/default
      dest: /etc/nginx/sites-available/default
      force: yes
      remote_src: True
    #when: first_run|changed 

  - name: configure nginx conf
    copy:
      src: /home/ubuntu/checkbox/local-conf/nginx.conf
      dest: /etc/nginx/nginx.conf
      force: yes
      remote_src: True
    #when: first_run|changed   

  - name: Restart nginx
    service:
      name: nginx
      state: restarted
    #when: first_run|changed

  - name: npm install
    npm:
      path: /home/ubuntu/checkbox/server-side/site/
      state: present
  
  - name: start node server
    environment: 
      MONGO_PORT: 3002
      MONGO_IP: localhost
      MONGO_USER: "{{ vault['mongo_user'] }}"
      MONGO_PASSWORD: "{{ vault['mongo_pass'] }}"
    shell: node server.js
    async: 2592000
    poll: 0
    args:
      chdir: /home/ubuntu/checkbox/server-side/site/
