- name: disable startup screen
  lineinfile:
    path: /etc/default/jenkins
    line: 'JAVA_ARGS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'
    regexp: '^JAVA_ARGS='

# should execute only at jenkins first run
- name: create custom init scripts directory
  file:
    path: /var/lib/jenkins/init.groovy.d
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0775
  when: jenkins_install|changed

- name: configure default users
  template:
    src: basic-security.groovy.j2
    dest: /var/lib/jenkins/init.groovy.d/basic-security.groovy
    owner: jenkins
    group: jenkins
    mode: 0775
  when: jenkins_install|changed

- name: Restart jenkins
  service:
    name: jenkins
    state: restarted
  when: jenkins_install|changed

- name: Wait for Jenkins to start up before proceeding.
  shell: "curl -D - --silent --max-time 5 http://localhost:8080/cli/"
  register: result
  until: (result.stdout.find("403 Forbidden") != -1) or (result.stdout.find("200 OK") != -1) and (result.stdout.find("Please wait while") == -1)
  retries: 5
  delay: 5
  changed_when: false
  when: jenkins_install|changed

- name: Remove Jenkins security init scripts after first startup.
  file:
    path: /var/lib/jenkins/init.groovy.d/basic-security.groovy
    state: absent
  when: jenkins_install|changed

- name: Install plugins
  jenkins_plugin:
    name: "{{ item }}"
    state: present
    timeout: 60
    url_username: "{{ vault['jenkins_user'] }}"
    url_password: "{{ vault['jenkins_pass'] }}"
  with_items:
    - workflow-aggregator
    - github-branch-source
    - postbuild-task
  retries: 5
  register: plugin_install

- name: Restart jenkins
  service:
    name: jenkins
    state: restarted
  when: plugin_install|changed