---
- hosts: nomad_instances
  become: yes

  pre_tasks:

  - name: Disable Firewall
    service: name=ufw state=stopped

  - name: Copy Job File
    become: no
    copy: src=templates/service.nomad dest=/home/{{ ansible_user }}/service.nomad

  roles:

    - role: brianshumate.nomad
      nomad_bind_address: 0.0.0.0
