---
- hosts: localhost
  gather_facts: no

  tasks:

  - name: Get credentials from vault
    include_vars:
      file: password.yml
      name: vault

  - name: Get vars from host
    include_vars:
      file: hosts.yml
      name: ec2_hosts

  - name: Create pem file
    copy:
      content: "{{ vault['aws_key']}}"
      dest: "{{ key_file_path }}"
      force: yes
      mode: 0400

  - name: Install pip dependency
    pip:
      name: boto
      state: present

  - name: Add Jenkins ec2 host
    add_host:
      name: "{{ ec2_hosts['jenkins'] }}"
      groups: jenkins
      ansible_ssh_user: ubuntu
      ansible_ssh_private_key_file: "{{ ec2_hosts['key_file_path'] }}"
      ansible_python_interpreter: /usr/bin/python
      host_key_checking: false

  - name: Check Jenkins instance is live
    wait_for: 
      host: "{{ ec2_hosts['jenkins'] }}"
      port: 22 
      delay: 60 
      timeout: 320 
      state: started

- hosts: jenkins
  gather_facts: no
  become: yes
  
  pre_tasks:
  
  - name: 'Install python2'
    raw: sudo apt -y update && sudo apt -y install python-simplejson

  tasks:

  - name: Get credentials
    include_vars:
      file: password.yml
      name: vault

  - name: Update packages
    apt:
      update_cache: yes
      upgrade: dist

  - import_tasks: install_dependencies.yaml
  
  - import_tasks: configure_jenkins.yaml

  - name: Wait for Jenkins
    shell: "curl -D - --silent --max-time 5 http://localhost:8080/cli/"
    register: result
    until: (result.stdout.find("403 Forbidden") != -1) or (result.stdout.find("200 OK") != -1) and (result.stdout.find("Please wait while") == -1)
    retries: 5
    delay: 5
    changed_when: false
  
  - import_tasks: copy_files.yaml

  - import_tasks: checkbox_job.yaml
  
  - import_tasks: itrust_job.yaml
